name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  build-preview:
    uses: ./.github/workflows/reusable-build.yml
    permissions: # TODO: Move this to cd.yml
      id-token: write
      contents: read 
    secrets: inherit # TODO: Move this to cd.yml
    with:
      bump-command: "local-bump"
      branch-name: ${{ github.head_ref }}